"use client"
import { motion } from "framer-motion";
import { Badge } from "../ui/badge";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "../ui/accordion";
import { Roboto, Saira } from 'next/font/google'

const saira = Saira({
  weight: '400',
  subsets: ['latin'],
})

export default function FrequentQuestions() {
    return (
      <section id="faq" className={`w-full py-20 md:py-32 ${saira.className}`}>
      <div className="px-4 md:px-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="flex flex-col items-center justify-center space-y-4 text-center mb-12"
        >
          <Badge className="rounded-full px-4 py-1.5 text-sm font-medium" variant="secondary">
            FAQ
          </Badge>
          <h2 className="text-3xl md:text-4xl font-bold tracking-tight">Frequently Asked Questions</h2>
          <p className="max-w-[800px] text-muted-foreground md:text-lg">
            Find answers to common questions about our platform.
          </p>
        </motion.div>

        <div className="mx-auto max-w-3xl">
          <Accordion type="single" collapsible className="w-full">
            {[
              {
                question: "Are the gradients unique?",
                answer:
                  "Yes, each gradient generated by our AI is unique. While some may share similar color palettes or styles, the exact blend and transition are distinct for each generated image.",
              },
              {
                question: "What file formats are the gradients provided in?",
                answer:
                  "We provide gradients primarily in high-quality PNG format.",
              },
              {
                question: "Can I use the gradients for commercial projects?",
                answer:
                  "Yes, our standard license allows for use in commercial projects, such as your business landing pages, client websites, or marketing materials.",
              },
              {
                question: "Do you offer any free samples?",
                answer:
                  "Yes, we offer a selection of free sample gradients so you can test their quality and compatibility with your projects before making a purchase. You can find them in our free-tier section",
              },
              {
                question: "How do I receive the gradients after purchase?",
                answer:
                  "After your purchase is complete, you will receive an email with a download link, or you can access your purchased gradients directly from your account dashboard on our website.",
              },
              {
                question: "Can I request a custom gradient?",
                answer:
                  "While we don't offer individual custom gradient design services at this moment, we are always open to suggestions and feedback. If there's a particular style or color palette you'd like to see, let us know! We might consider it for future AI model training or curated collections.",
              },
            ].map((faq, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 10 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.3, delay: i * 0.05 }}
              >
                <AccordionItem value={`item-${i}`} className="border-b border-border/40 py-2">
                  <AccordionTrigger className="text-left font-medium hover:no-underline rounded-b-none mb-4 border-b-amber-100/20 border-b-[1px]">
                    {faq.question}
                  </AccordionTrigger>
                  <AccordionContent className="text-muted-foreground">{faq.answer}</AccordionContent>
                </AccordionItem>
              </motion.div>
            ))}
          </Accordion>
        </div>
      </div>
    </section>

    )
}